import Capacitor
import UIKit

/// Registers plugins that live in the app target itself.
///
/// Capacitor only auto-registers what it finds in `packageClassList` inside
/// the bundled capacitor.config.json (see CapacitorBridge.registerPlugins()),
/// and that list is generated by `npx cap sync` from installed npm plugin
/// packages. A plugin compiled directly into this app target — as
/// `CallerIdIndexPlugin` is — never appears there, so without this subclass
/// the JS side gets `{"code":"UNIMPLEMENTED"}` on every call even though the
/// Swift file compiles fine.
///
/// `capacitorDidLoad()` is Capacitor's supported hook for exactly this. Note
/// that this class is wired up in SceneDelegate, not in Main.storyboard: this
/// app's scene builds its root view controller in code, so the storyboard's
/// custom class is never consulted and editing it has no effect.
class MainViewController: CAPBridgeViewController {
    override open func capacitorDidLoad() {
        bridge?.registerPluginType(CallerIdIndexPlugin.self)
    }
}
