import Capacitor
import UIKit

/// Registers plugins that live in the app target itself.
///
/// Capacitor only auto-registers what it finds in `packageClassList` inside
/// the bundled capacitor.config.json (see CapacitorBridge.registerPlugins()),
/// and that list is generated by `npx cap sync` from installed npm plugin
/// packages. A plugin compiled directly into this app target — as
/// `CallerIdIndexPlugin` is — never appears there, so without this subclass
/// the JS side gets `{"code":"UNIMPLEMENTED"}` on every call even though the
/// Swift file compiles fine.
///
/// `capacitorDidLoad()` is Capacitor's supported hook for exactly this. It
/// runs from `loadView()`, so only a controller that actually loads registers
/// anything.
///
/// This class is named in Main.storyboard, and nowhere else. The scene
/// manifest sets UISceneStoryboardFile, so UIKit instantiates the storyboard's
/// initial view controller and installs it in a window before
/// `scene(_:willConnectTo:)` ever runs. SceneDelegate used to build a second
/// window around its own MainViewController, which left two bridges — two
/// webviews, both running the JS, only one of them holding this registration —
/// and whichever window became key decided whether the plugin existed at all.
class MainViewController: CAPBridgeViewController {
    override open func capacitorDidLoad() {
        bridge?.registerPluginType(CallerIdIndexPlugin.self)
    }
}
